app:
  message-transport: kafka
  telegram-token: ${TELEGRAM_TOKEN} # env variable
  kafka:
    topics:
      requests: user.commands
      responses: user.responses
      updates: link.updates
      dlq: dead_letter_queue

spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: bot-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: backend.academy.common.dto.kafka.request,backend.academy.common.dto.kafka.response
        spring.json.value.default.type: backend.academy.common.dto.kafka.response.KafkaBotResponse
  application:
    name: Bot
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 8080

client:
  port: 8081
  host: api

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
